### ISSUE TITLE
STL files for the 3Dpart?

### ISSUE THREAD

**Issue by TRP-Retromods** [keoni29/romclient#1]
Hi there! I'm really interest into the 3Dprinting housing you've done for your cartridge reader. I'm currently making an Atari 2600 adapter for the Retrode 2, and I need to make one too. I was planning to buy a cartridge and make on on my side but you wrote that you'd publish the STL file eventually.

I'd like to use yours as a reference.
Are you still planning to publish it? If yes when do you think you will?

Best regards,

**Comment by keoni29** [comment]
Hi TRP, I dropped the files on https://hackaday.io/project/113217-atari2600-cartridge-reader
I included the STEP file, which makes it easier to modify.

**Comment by TRP-Retromods** [comment]
Thank you very much!
